version: '3.8'

services:
  # Базы данных
  db:
    image: postgres:17
    container_name: yadro_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=randomuser_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    command: postgres -c max_connections=200
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7
    container_name: yadro_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --maxmemory 64mb --maxmemory-policy allkeys-lru
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  # Приложение
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: yadro_backend
    ports:
      - "8000:8000" # В реальном prod не нужно
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:1234@db:5432/randomuser_db
      - REDIS_URL=redis://redis:6379/0
      - ENVIRONMENT=production
    command: >
      sh -c "alembic upgrade head && 
      gunicorn -k uvicorn.workers.UvicornWorker -w 2 -b 0.0.0.0:8000 --timeout 60 --graceful-timeout 30 app.main:app"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app-network
    logging:
      driver: loki
      options:
        # Адрес Loki, куда складывать логи
        # Обратите внимание, что здесь используется не имя сервиса loki, а локальный хост, на который проброшен порт Loki,
        # это сделано потому, что логи будет писать docker engine, который расположен на хостовой машине,
        # и он не знает имени хоста контейнера Loki, которое ему присвоил compose во внутренней сети проекта.
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-batch-size: "100"
        loki-retries: 3
        loki-max-backoff: 1000ms
        loki-timeout: 2s
        mode: non-blocking
        max-buffer-size: 4m
        loki-external-labels: "container_name={{.Name}},job=fastapi"

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    # volumes:
    # Для SSL сертификатов:
    # - ./path/to/certs:/etc/nginx/certs:ro
    networks:
      - app-network
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-batch-size: "100"
        loki-retries: 3
        loki-max-backoff: 1000ms
        loki-timeout: 2s
        mode: non-blocking
        max-buffer-size: 4m
        loki-external-labels: "container_name={{.Name}},job=nginx"

  # Мониторинг
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./backend/monitoring/loki-config.yaml:/etc/loki/local-config.yaml:ro
      - loki_data:/loki
    networks:
      - app-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./backend/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheusdata:/prometheus
    networks:
      - app-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./backend/monitoring/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./backend/monitoring/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml:ro
      - grafanadata:/var/lib/grafana
    depends_on:
      - prometheus
      - loki
    networks:
      - app-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: yadro_postgres_exporter
    volumes:
      - ./backend/monitoring/grafana/custom_metrics/custom_pg_queries.yaml:/etc/postgres_exporter/custom_pg_queries.yaml:ro
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:1234@db:5432/randomuser_db?sslmode=disable
      - PG_EXPORTER_EXTEND_QUERY_PATH=/etc/postgres_exporter/custom_pg_queries.yaml
    ports:
      - "9187:9187"
    depends_on:
      db:
        condition: service_healthy
      prometheus:
        condition: service_started
    networks:
      - app-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: yadro_redis_exporter
    environment:
      - REDIS_ADDR=redis://redis:6379
    ports:
      - "9121:9121"
    depends_on:
      redis:
        condition: service_healthy
      prometheus:
        condition: service_started
    networks:
      - app-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx_exporter
    command: -nginx.scrape-uri http://nginx:80/nginx_status
    ports:
      - "9113:9113"
    depends_on:
      - nginx
    networks:
      - app-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - app-network
    depends_on:
      - prometheus
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
    networks:
      - app-network
    depends_on:
      - prometheus
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  db_data:
  grafanadata:
  prometheusdata:
  loki_data:
  redis_data:

networks:
  app-network:
    driver: bridge
