version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:1234@db:5432/randomuser_db
    command: >
      sh -c "alembic upgrade head && 
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 2"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    networks:
      - app-network

  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=randomuser_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: npm start
    volumes:
      - ./frontend:/app
      - /app/node_modules # Сохраняем node_modules в контейнере
    depends_on:
      - app
    environment:
      - CHOKIDAR_USEPOLLING=true # Для горячей перезагрузки в Docker
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
