global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "fastapi"
    metrics_path: /metrics
    static_configs:
      - targets: [ "backend:8000" ]
        labels:
          app: "yadro_backend"
#  - job_name: "docker"
#    static_configs:
#      - targets: ["cadvisor:8080"]  # Для мониторинга контейнеров
