pg_stat_activity_query_duration:
  query: |
    SELECT 
      datname,
      count(*) AS slow_queries,
      state
    FROM pg_stat_activity
    WHERE state = 'active' AND now() - query_start > '1s'::interval
    GROUP BY datname, state;
  metrics:
    - datname:
        usage: "LABEL"
        description: "Database name"
    - state:
        usage: "LABEL"
        description: "Connection state"
    - slow_queries:
        usage: "GAUGE"
        description: "Number of currently active queries longer than 1 second"
