name: Test Docker Workflow

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.36.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Проверка установки

      - name: Build and start services
        run: |
          docker-compose -f docker-compose.yml up -d --build

      - name: Check containers
        run: |
          docker-compose ps
          # Проверяем, что все контейнеры запущены
          if [ "$(docker-compose ps -q | wc -l)" -eq "$(docker-compose ps -q --status=running | wc -l)" ]; then
            echo "All containers are running."
          else
            echo "Some containers are not running!"
            docker-compose ps
            exit 1
          fi

      - name: Wait for services start
        run: |
          timeout=15
          elapsed=0
          while ! curl --silent --fail http://localhost:8000/docs && [ $elapsed -lt $timeout ]; do
            echo "Waiting for services to be ready..."
            sleep 5
            elapsed=$((elapsed + 5))
          done
          if [ $elapsed -ge $timeout ]; then
            echo "services did not become ready in time!"
            exit 1
          fi
          echo "services is ready!"

      - name: Shut down Docker Compose
        run: |
          docker-compose down
